"""
backend/scripts/gen_demo_data.py — generate the frontend demo-mode fixtures.

Runs the live pipeline for a curated set of handbook customers and writes
frontend/src/demoData.ts. The dashboard uses these precomputed responses when
VITE_DEMO_MODE=true, so it demos fully even if the backend is asleep/unavailable.

Deterministic: FLAN-T5 is disabled so replies come from the template path.

    python backend/scripts/gen_demo_data.py
"""

import json
import os
import sys

os.environ.setdefault("LULU_DISABLE_FLAN", "1")

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from backend.pipeline import resolve  # noqa: E402

# (customer_id, short label for the chip, demo complaint message)
_PRESETS = [
    ("C0018", "Platinum · cracked TV", "The TV arrived with a cracked screen and will not turn on."),
    ("C0013", "Electronics defect", "The laptop I received is defective and the screen is broken."),
    ("C0001", "Serial refunder", "I demand my money back immediately, this is absolutely unacceptable!"),
    ("C0016", "First purchase", "My very first order still has not arrived, where is my package?"),
    ("C0005", "Perishable order", "The groceries were spoiled and the packaging was badly damaged."),
    ("C0020", "Low-value query", "I have a small question, the app keeps loading slowly at checkout."),
    ("C0034", "Logged promise", "Your agent promised me a replacement on my last call about this order."),
    ("C0006", "Abuser + promise", "You assured me a replacement last time, I want it processed now."),
]


def main() -> None:
    presets = []
    data = {}
    for cid, label, message in _PRESETS:
        result = resolve(message, cid)
        presets.append({"customer_id": cid, "label": label, "message": message})
        data[cid] = result

    out_dir = os.path.join(_ROOT, "frontend", "src")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "demoData.ts")

    header = (
        "// AUTO-GENERATED by backend/scripts/gen_demo_data.py — do not edit by hand.\n"
        "// Regenerate:  python backend/scripts/gen_demo_data.py\n"
        "import type { ResolveResponse } from \"./types\";\n\n"
        "export interface DemoPreset {\n"
        "  customer_id: string;\n  label: string;\n  message: string;\n}\n\n"
    )
    body = (
        "export const DEMO_PRESETS: DemoPreset[] = "
        + json.dumps(presets, indent=2)
        + ";\n\nexport const DEMO_DATA: Record<string, ResolveResponse> = "
        + json.dumps(data, indent=2)
        + ";\n"
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(header + body)

    print(f"Wrote {out_path} ({len(data)} presets)")
    for cid, _, _ in _PRESETS:
        e = data[cid]["economist"]
        print(f"  {cid}: {e['action']:<12} email={e['email_trigger']}")


if __name__ == "__main__":
    main()
